import ElephantCongrats from '../assets/images/ele_congrats.png';

export const characterData = [
  {
    id: 1,
    tags: ["social", "extroverted", "encouraging", "rebellious", "independent"],
    position: "right",
    bgColor: "#06A59A",
    description: "Representative of The End of Software",
    congratsImg: ElephantCongrats,
    title: "SaaSy",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Sassy.png",
    pronoun: "They/Them",
    trailheadText: "Salesforce Culture and Values",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 2,
    tags: [
      "Faithful",
      "happy",
      "curious",
      "inspiring",
      "joyful",
      "caring",
      "versatile",
    ],
    position: "left",
    congratsImg: ElephantCongrats,
    bgColor: "#C5CDFC",
    description: "Representative of community and inclusion",
    title: "Astro Nomical",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Astro.png",
    pronoun: "They/Them",
    trailheadText: "Get Started with Trailhead",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 3,
    tags: [
      "Smart",
      "nimble",
      "innovative",
      "knowledgeable",
      "forward-thinking",
    ],
    position: "left",
    congratsImg: ElephantCongrats,
    bgColor: "#C2E3FF",
    description:
      "Representative of Einstein Product and AI Innovation at Salesforce",
    title: "Einstein",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Einstien.png",
    pronoun: "He/Him",
    trailheadText: "Get Smart with Salesforce Einstein",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 4,
    tags: ["charming", "outgoing", "bold", "fearless", "unexpected"],
    description: "Representative of Salesforce Developers",
    bgColor: "#7483D8",
    congratsImg: ElephantCongrats,
    position: "right",
    title: "Codey the Bear",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Codey.png",
    pronoun: "He/Him",
    trailheadText: "Develop Apps for Slack",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 5,
    tags: [
      "Trustworthy",
      "sure-footed",
      "helpful",
      "confident",
      "unique",
    ],
    description: "Representative of Salesforce Admins",
    title: "Cloudy the Goat",
    congratsImg: ElephantCongrats,
    bgColor: "#8DE0DD",
    position: "left",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrationsCloudy.png",
    pronoun: "She/Her",
    trailheadText: "Flow Builder Logic",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 6,
    tags: ["Adaptable", "analytical", "adventurous", "approachable"],
    description: "Representative of Salesforce Marketers",
    title: "Brandy the Fox",
    congratsImg: ElephantCongrats,
    bgColor: "#FF92BE",
    position: "right",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Brandy.png",
    pronoun: "She/Her",
    trailheadText: "Roles and Responsibilities for Marketing Teams",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 7,
    tags: ["Responsible", "universal", "technical", "humble"],
    description: "Representative of Salesforce Architects",
    title: "Ruth the Elephant",
    congratsImg: ElephantCongrats,
    bgColor: "#C5CDFC",
    position: "left",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Ruth.png",
    pronoun: "They/Them",
    trailheadText: "Advanced Apex Specialist",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 8,
    tags: ["Brave", "resilient", "strategic"],
    description: "Representative of the Salesblazer Community",
    title: "Zig the Zebra",
    congratsImg: ElephantCongrats,
    bgColor: "#8DE0DD",
    position: "right",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2023/05/2023-05-360Blog-ContextualDriver-Zig-567x844-1.png",
    pronoun: "She/Her",
    trailheadText: "Sales Cloud Basics",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 9,
    tags: ["reliable", "spirited", "playful", "kind", "adoring"],
    description: "Representative of love and longevity",
    title: "Koa the Dog",
    congratsImg: ElephantCongrats,
    bgColor: "#FFB5D3",
    position: "left",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Koa.png",
    pronoun: "He/Him",
    trailheadText: "Salesforce Essentials for Small Business",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 10,
    tags: ["Resilient", "Hard-working", "Collaborative"],
    description:
      "Representative of Salesforce Flow and its passionate fanbase of Flownatics, automation, agility, and community",
    title: "Flo the Flying Squirrel",
    bgColor: "#BEC7F6",
    congratsImg: ElephantCongrats,
    position: "right",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2023/03/2023-03-360Blog-Flo-567-844.png",
    pronoun: "He/Him",
    trailheadText: "Learn More About Salesforce Flow",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 11,
    tags: ["Motivated", "entrepreneurial"],
    description: "Representative of Partners",
    title: "Appy the Bobcat",
    congratsImg: ElephantCongrats,
    bgColor: "#7BD1F8",
    position: "left",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Appy.png",
    pronoun: "She/her",
    trailheadText: "Salesforce Partner Community",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
  {
    id: 12,
    tags: ["Fun", "resourceful"],
    congratsImg: ElephantCongrats,
    description: "Representative of all things MuleSoft",
    title: "Max the Mule",
    bgColor: "#06A59A",
    position: "left",
    image: "https://www.salesforce.com/blog/wp-content/uploads/sites/2/2021/12/2021-12-360Blog-2D-IndividualIllustrations-Max.png",
    pronoun: "He/Him",
    trailheadText: "Data Integration Specialist",
    trailheadBadge:
      "https://trailhead.salesforce.com/content/learn/modules/roles-and-responsibilities-for-marketing-teams?trail_id=personalize_customer_journeys_marketing_cloud?&utm_source=salesforce&utm_medium=blog-360&utm_campaign=trailblazer_blog&utm_content=tbc_apr24_salesforcecharacters&icid=SFBLOG:tbc-blog:7010M0000025ltGQAQ&_ga=2.232064219.536382854.1726036616-890700713.1724145521",
  },
];
